import APIResponseError from "./APIResponseError";

/**
 * Represents the http body of a {@link APIResponse}
 * generated by the chexxo server api.
 */
export default class APIResponseBody {
  constructor(
    /**
     * Contains the error if one occured. Else
     * this field contains `null`.
     */
    readonly error: APIResponseError,
    /**
     * Contains the pem-formated certificate
     * if no error occured. Else this field
     * contains `null`.
     */
    readonly certificate: string
  ) {}
}
